import type { ExperienceItem } from "@/content/portfolio/types";

export const experience: ExperienceItem[] = [
  {
    id: "exp-crespassos",
    category: "experience",
    titleKey: "experience_cr_espassos_name",
    org: "CR Espassos",
    descriptionKey: "experience_cr_espassos_description",
    detailsKey: "experience_cr_espassos_details",
    link: "https://crespassos.com",
    techs: ["Revit", "AutoCAD"],
    dateStart: new Date("2022-09-01"),
    dateEnd: new Date("2023-08-31"),
    hasDetailsPage: true,
  },
  {
    id: "exp-subvisual",
    category: "experience",
    title: "Full-Stack Developer Apprentice",
    org: "Subvisual",
    descriptionKey: "experience_subvisual_description",
    detailsKey: "experience_subvisual_details",
    link: "https://subvisual.com",
    techs: [
      "React",
      "TypeScript",
      "Joy UI",
      "TanStack Query",
      "Supabase",
      "PostgreSQL",
      "Solidity",
      "Wagmi",
    ],
    dateStart: new Date("2023-12-01"),
    dateEnd: new Date("2024-02-29"),
    featured: true,
    hasDetailsPage: true,
  },
  {
    id: "exp-talent-protocol",
    category: "experience",
    title: "Full-Stack Developer",
    org: "Talent Protocol",
    descriptionKey: "experience_talent_protocol_description",
    detailsKey: "experience_talent_protocol_details",
    link: "https://www.talentprotocol.com",
    techs: [
      "React",
      "Next.js",
      "TypeScript",
      "Joy UI",
      "Wagmi",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2024-03-01"),
    dateEnd: new Date("2025-02-28"),
    featured: true,
    hasDetailsPage: true,
  },
  {
    id: "exp-aquasis",
    category: "experience",
    title: "Frontend Developer",
    org: "Aquasis",
    descriptionKey: "experience_aquasis_description",
    detailsKey: "experience_aquasis_details",
    link: "https://www.aquasis.pt",
    techs: ["React", "TypeScript", "Zustand", "Bootstrap", "PostgreSQL"],
    dateStart: new Date("2025-01-01"),
    dateEnd: null,
    featured: true,
    hasDetailsPage: true,
  },
];
