import type { ProjectItem } from "@/content/portfolio/types";

export const projects: ProjectItem[] = [
  {
    id: "proj-wordlechain",
    category: "projects",
    title: "Wordlechain",
    org: "Subvisual",
    subjectKey: "project_wordlechain_subject",
    descriptionKey: "project_wordlechain_description",
    detailsKey: "project_wordlechain_details",
    link: "https://wordlechain.pages.dev",
    repo: "https://github.com/thetiagogil/12-wordlechain",
    techs: ["React", "TypeScript", "MUI", "Wagmi", "Solidity", "Blockchain"],
    dateStart: new Date("2023-12-05"),
    status: "completed",
    type: "early work",
    featured: false,
    hasDetailsPage: true,
    images: [
      "projects/wordlechain/wordlechain-1.png",
      "projects/wordlechain/wordlechain-2.png",
      "projects/wordlechain/wordlechain-3.png",
    ],
  },
  {
    id: "proj-giraffes-vs-sea",
    category: "projects",
    title: "Giraffes vs Sea",
    subjectKey: "project_giraffes_vs_sea_subject",
    descriptionKey: "project_giraffes_vs_sea_description",
    detailsKey: "project_giraffes_vs_sea_details",
    link: "https://thetiagogil.github.io/01-giraffes-vs-sea",
    repo: "https://github.com/thetiagogil/01-giraffes-vs-sea",
    techs: ["HTML", "CSS", "JavaScript"],
    dateStart: new Date("2023-08-01"),
    status: "completed",
    type: "early work",
    featured: false,
    hasDetailsPage: true,
    images: ["projects/giraffes-vs-sea/giraffes-vs-sea-1.png"],
  },
  {
    id: "proj-house-of-legends",
    category: "projects",
    title: "House of Legends",
    subjectKey: "project_house_of_legends_subject",
    descriptionKey: "project_house_of_legends_description",
    detailsKey: "project_house_of_legends_details",
    techs: ["React", "TypeScript"],
    dateStart: new Date("2023-09-01"),
    status: "unavailable",
    type: "early work",
    featured: false,
    hasDetailsPage: true,
    images: [],
  },
  {
    id: "proj-fin-ace",
    category: "projects",
    title: "Fin/Ace",
    subjectKey: "project_fin_ace_subject",
    descriptionKey: "project_fin_ace_description",
    detailsKey: "project_fin_ace_details",
    techs: ["React", "TypeScript"],
    dateStart: new Date("2023-10-01"),
    status: "completed",
    type: "early work",
    featured: false,
    hasDetailsPage: true,
    images: [],
  },
  {
    id: "proj-poketracker",
    category: "projects",
    title: "Poketracker",
    subjectKey: "project_poketracker_subject",
    descriptionKey: "project_poketracker_description",
    detailsKey: "project_poketracker_details",
    techs: [
      "Next.js",
      "TypeScript",
      "Shadcn/UI",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2025-10-01"),
    status: "in progress",
    type: "core",
    featured: true,
    hasDetailsPage: true,
    images: [
      "projects/poketracker/poketracker-1.png",
      "projects/poketracker/poketracker-2.png",
      "projects/poketracker/poketracker-3.png",
      "projects/poketracker/poketracker-4.png",
    ],
  },
  {
    id: "proj-uparque",
    category: "projects",
    title: "Uparque",
    subjectKey: "project_uparque_subject",
    descriptionKey: "project_uparque_description",
    detailsKey: "project_uparque_details",
    techs: ["React", "TypeScript", "MUI"],
    dateStart: new Date("2026-04-01"),
    status: "in progress",
    type: "product",
    featured: true,
    hasDetailsPage: true,
    images: [],
  },
];
