export type {
  BaseDataItem,
  Category,
  CertificationItem,
  DataItem,
  DetailItem,
  DetailLink,
  EducationItem,
  ExperienceItem,
  ItemStatus,
  ProjectDataSource,
  ProjectItem,
  ProjectScope,
  ProjectType,
  ShowcaseItem,
} from "@/content/portfolio/types";
