import type { ProjectItem } from "@/content/portfolio/types";

export const onesbryne: ProjectItem = {
  id: "proj-onesbryne",
  category: "projects",
  title: "Onesbryne",
  subjectKey: "project.onesbryne.subject",
  summaryKey: "project.onesbryne.summary",
  detailKey: "project.onesbryne.detail",
  link: "https://onesbryne.vercel.app/",
  repo: "https://github.com/thetiagogil/08-onesbryne",
  techs: [
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Radix UI",
    "Supabase",
    "PostgreSQL",
  ],
  dateStart: new Date("2024-06-01"),
  status: "completed",
  type: "product",
  scope: "ecommerce",
  dataSource: "dedicated-database",
  featured: true,
  hasDetailsPage: true,
  images: [
    "projects/onesbryne/onesbryne-1.png",
    "projects/onesbryne/onesbryne-2.png",
    "projects/onesbryne/onesbryne-3.png",
    "projects/onesbryne/onesbryne-4.png",
    "projects/onesbryne/onesbryne-5.png",
    "projects/onesbryne/onesbryne-6.png",
  ],
};
