import type { ProjectItem } from "@/content/portfolio/types";

export const talio: ProjectItem = {
  id: "proj-talio",
  category: "projects",
  title: "Talio",
  org: "Subvisual",
  subjectKey: "project.talio.subject",
  summaryKey: "project.talio.summary",
  detailKey: "project.talio.detail",
  link: "https://tal-io.pages.dev/personal/profile",
  repo: "https://github.com/thetiagogil/05-talio",
  techs: ["React", "TypeScript", "Material UI"],
  dateStart: new Date("2024-02-01"),
  status: "completed",
  type: "early-work",
  scope: "team-planner",
  dataSource: "local-storage",
  featured: false,
  hasDetailsPage: true,
  images: [
    "projects/talio/talio-1.png",
    "projects/talio/talio-2.png",
    "projects/talio/talio-3.png",
    "projects/talio/talio-4.png",
    "projects/talio/talio-5.png",
    "projects/talio/talio-6.png",
    "projects/talio/talio-7.png",
  ],
};
